destination:
  server: https://kubernetes.default.svc
source:
  repoURL: ${GITEA_URL}/${GITEA_USER}/dag
  targetRevision: HEAD
gitea:
  server:
    outClusterURL: ${GITEA_URL}
    inClusterURL: ${GITEA_INTERNAL_URL}
  oAuthSecret: demo-oauth-${GITEA_USER}-secret
  username: ${GITEA_USER}
  password: ${GITEA_USER}@123
drone:
  server:
    version: support-host-aliases
    host: ${DRONE_SERVER_URL}
    namespace: drone
    hostAliases:
      - ip: ${GITEA_HTTP_CLUSTER_IP}
        hostnames:
        - ${GITEA_URL}