destination:
  server: https://kubernetes.default.svc
source:
  repoURL: http://gitea-127.0.0.1.sslip.io:30950//dag.git
  targetRevision: HEAD
gitea:
  server:
    outClusterURL: http://gitea-127.0.0.1.sslip.io:30950
    inClusterURL: 
  oAuthSecret: demo-oauth--secret
  username: 
  password: @123
drone:
  server:
    version: support-host-aliases
    host: http://drone-127.0.0.1.sslip.io:30980
    namespace: drone
    hostAliases:
      - ip: 
        hostnames:
        - gitea-127.0.0.1.sslip.io