apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: drone
resources:
- https://github.com/kameshsampath/drone-tutorial-gitea-helper/blob/main/manifests/install.yaml
## add your overrides